### PR TITLE
Add Favicon 

### PR DESCRIPTION
**Pull request by aswanthkoleri**
This is the PR for the Issue #1 .

### CODE REVIEW

**Comment by aswanthkoleri** [comment]
Here is the Demo : https://aswanthkoleri.github.io/fossiiita.github.io/

**Comment by Anupam-dagar** [comment]
can you remove the white background?

**Comment by aswanthkoleri** [comment]
No I couldnt remove the white background . I Tried .

**Comment by Anupam-dagar** [comment]
okay

**Pull request closed without merging**
